baseURL = "https://www.maopanfeng.com/"
title = "Growth Investing"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[outputs]
home = ["HTML", "JSON"]

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1

  [languages.cn]
    contentDir = "content/cn"
    languageName = "中文"
    weight = 2
    languageCode = "zh-cn"

[params]
  description = "A lifelong notebook on investing, learning, family and life."

[params.giscus]
    repo = "maopanfeng/www"
    repoid = "R_kgDORQEPOg"
    category = "Announcements"
    categoryid = "DIC_kwDORQEPOs4C2aWQ"
    mapping = "pathname"
    strict = "0"
    reactionsenabled = "1"
    emitmetadata = "0"
    inputposition = "bottom"
    theme = "preferred_color_scheme"

[[languages.en.menu.main]]
  name = "Genius"
  url = "/genius/"
  weight = 10
[[languages.en.menu.main]]
  name = "Stocks"
  url = "/stocks/"
  weight = 20
[[languages.en.menu.main]]
  name = "Notes"
  url = "/notes/"
  weight = 30
[[languages.en.menu.main]]
  name = "Blogs"
  url = "/blogs/"
  weight = 40
[[languages.en.menu.main]]
  name = "Books"
  url = "/books/"
  weight = 50
[[languages.en.menu.main]]
  name = "Wiki"
  url = "/wiki/"
  weight = 60
[[languages.en.menu.main]]
  name = "About"
  url = "/about/"
  weight = 70

[[languages.cn.menu.main]]
  name = "Genius"
  url = "/cn/genius/"
  weight = 10
[[languages.cn.menu.main]]
  name = "Stocks"
  url = "/cn/stocks/"
  weight = 20
[[languages.cn.menu.main]]
  name = "Notes"
  url = "/cn/notes/"
  weight = 30
[[languages.cn.menu.main]]
  name = "Blogs"
  url = "/cn/blogs/"
  weight = 40
[[languages.cn.menu.main]]
  name = "Books"
  url = "/cn/books/"
  weight = 50
[[languages.cn.menu.main]]
  name = "Wiki"
  url = "/cn/wiki/"
  weight = 60
[[languages.cn.menu.main]]
  name = "About"
  url = "/cn/about/"
  weight = 70
