baseURL = "https://www.maopanfeng.com/"
title = "Maopanfeng"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[outputs]
home = ["HTML", "JSON"]

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1

  [languages.cn]
    contentDir = "content/cn"
    languageName = "中文"
    weight = 2
    languageCode = "zh-cn"

# 核心修正：填入你提供的 Giscus 真实 ID
[params.giscus]
    repo = "maopanfeng/blog"
    repoId = "R_kgDORQEPOg"
    category = "Announcements"
    categoryId = "DIC_kwDORQEPOs4C2aWQ"
    mapping = "pathname"
    strict = "0"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "preferred_color_scheme"
